# Branch Protection Rules
# This file defines the branch protection rules for the repository

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Check code formatting"
          - "Type checking"
          - "Run tests with coverage"
          - "Check code style"
          - "Security scan"
          - "Upload coverage report"
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false 