name: Branch Protection

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  protect:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hanging
    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Changed from 3.x to 3.11 for better compatibility
          cache: 'pip'  # Enable pip caching
          
      - name: Install core dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pip-tools
          pip config set global.only-binary :all:
          pip-compile --output-file=requirements.lock requirements.txt
          pip install -r requirements.lock --verbose
        timeout-minutes: 5  # Add timeout for this step
          
      - name: Install test dependencies
        run: |
          pip install --only-binary :all: pytest pytest-cov flake8 bandit black isort mypy types-requests types-beautifulsoup4 --verbose
          mypy --install-types
        timeout-minutes: 3  # Add timeout for this step
          
      - name: Create necessary directories
        run: |
          mkdir -p src tests
          
      - name: Format code
        run: |
          if [ -d "src" ]; then
            black src/
            isort src/
          fi
          if [ -d "tests" ]; then
            black tests/
            isort tests/
          fi
          
      - name: Commit formatting changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/ tests/
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: apply automatic code formatting" && git push)
          
      - name: Type checking
        run: |
          if [ -d "src" ]; then
            mypy --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs --check-untyped-defs --disallow-untyped-decorators --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-no-return --warn-unreachable --warn-return-any src/
          fi
          if [ -d "tests" ]; then
            mypy --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs --check-untyped-defs --disallow-untyped-decorators --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-no-return --warn-unreachable --warn-return-any tests/
          fi
          
      - name: Run tests with coverage
        id: test
        run: |
          if [ -d "tests" ]; then
            pytest --cov=src/ --cov-report=xml tests/
          else
            echo "No tests directory found. Skipping tests."
          fi
          
      - name: Check code style
        run: |
          if [ -d "src" ]; then
            flake8 src/
          fi
          if [ -d "tests" ]; then
            flake8 tests/
          fi
          
      - name: Security scan
        run: |
          if [ -d "src" ]; then
            bandit -r src/ -c pyproject.toml
          fi
          
      - name: Upload coverage report
        if: success() && steps.test.outcome == 'success'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 