name: Branch Protection

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit black isort mypy
          
      - name: Check code formatting
        run: |
          black --check src/ tests/
          isort --check-only src/ tests/
          
      - name: Type checking
        run: |
          mypy src/ tests/
          
      - name: Run tests with coverage
        run: |
          pytest --cov=src/ --cov-report=xml tests/
          
      - name: Check code style
        run: |
          flake8 src/ tests/
          
      - name: Security scan
        run: |
          bandit -r src/ -c pyproject.toml
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 